name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main
      - feat/**
    workflow_call:
    workflow_dispatch:

env:
  CI: false

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        if: always()
        run: |
          if git diff --name-only --diff-filter=d HEAD^1 | grep -q -E "(\.[jt]s$|\.tsx$|^pnpm-lock\.yaml$|^tsconfig\.json$)"; then
            NODE_OPTIONS=--max-old-space-size=8192 pnpm run typecheck --extendedDiagnostics
          fi
